apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odc-dispatcher-vol
  namespace: knative-eventing
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
