/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "knative.dev/eventing/pkg/apis/messaging/v1alpha1"
	scheme "knative.dev/eventing/pkg/client/clientset/versioned/scheme"
)

// OnDiskChannelsGetter has a method to return a OnDiskChannelInterface.
// A group's client should implement this interface.
type OnDiskChannelsGetter interface {
	OnDiskChannels(namespace string) OnDiskChannelInterface
}

// OnDiskChannelInterface has methods to work with OnDiskChannel resources.
type OnDiskChannelInterface interface {
	Create(*v1alpha1.OnDiskChannel) (*v1alpha1.OnDiskChannel, error)
	Update(*v1alpha1.OnDiskChannel) (*v1alpha1.OnDiskChannel, error)
	UpdateStatus(*v1alpha1.OnDiskChannel) (*v1alpha1.OnDiskChannel, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.OnDiskChannel, error)
	List(opts v1.ListOptions) (*v1alpha1.OnDiskChannelList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.OnDiskChannel, err error)
	OnDiskChannelExpansion
}

// onDiskChannels implements OnDiskChannelInterface
type onDiskChannels struct {
	client rest.Interface
	ns     string
}

// newOnDiskChannels returns a OnDiskChannels
func newOnDiskChannels(c *MessagingV1alpha1Client, namespace string) *onDiskChannels {
	return &onDiskChannels{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the onDiskChannel, and returns the corresponding onDiskChannel object, and an error if there is any.
func (c *onDiskChannels) Get(name string, options v1.GetOptions) (result *v1alpha1.OnDiskChannel, err error) {
	result = &v1alpha1.OnDiskChannel{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ondiskchannels").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of OnDiskChannels that match those selectors.
func (c *onDiskChannels) List(opts v1.ListOptions) (result *v1alpha1.OnDiskChannelList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.OnDiskChannelList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ondiskchannels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested onDiskChannels.
func (c *onDiskChannels) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ondiskchannels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a onDiskChannel and creates it.  Returns the server's representation of the onDiskChannel, and an error, if there is any.
func (c *onDiskChannels) Create(onDiskChannel *v1alpha1.OnDiskChannel) (result *v1alpha1.OnDiskChannel, err error) {
	result = &v1alpha1.OnDiskChannel{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ondiskchannels").
		Body(onDiskChannel).
		Do().
		Into(result)
	return
}

// Update takes the representation of a onDiskChannel and updates it. Returns the server's representation of the onDiskChannel, and an error, if there is any.
func (c *onDiskChannels) Update(onDiskChannel *v1alpha1.OnDiskChannel) (result *v1alpha1.OnDiskChannel, err error) {
	result = &v1alpha1.OnDiskChannel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ondiskchannels").
		Name(onDiskChannel.Name).
		Body(onDiskChannel).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *onDiskChannels) UpdateStatus(onDiskChannel *v1alpha1.OnDiskChannel) (result *v1alpha1.OnDiskChannel, err error) {
	result = &v1alpha1.OnDiskChannel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ondiskchannels").
		Name(onDiskChannel.Name).
		SubResource("status").
		Body(onDiskChannel).
		Do().
		Into(result)
	return
}

// Delete takes name of the onDiskChannel and deletes it. Returns an error if one occurs.
func (c *onDiskChannels) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ondiskchannels").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *onDiskChannels) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ondiskchannels").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched onDiskChannel.
func (c *onDiskChannels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.OnDiskChannel, err error) {
	result = &v1alpha1.OnDiskChannel{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ondiskchannels").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
